# This is a generated file. Not intended for manual editing.
version: "3.7"
services:
  mtls-grpc-server:
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    ports:
    - "127.0.0.1:57004:57100"
    - "127.0.0.1:57204:57300"
    volumes:
    - "C:\\Users\\Friday\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.2.1\\\
      Linux64:/riderDebugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.1.2/bin:/riderLogsConf"
    - "C:\\Users\\Friday\\AppData\\Local\\JetBrains\\Rider2023.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_8_30_15_51_29:/riderLogs:rw"
